<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hockey [

<!ELEMENT hockey (league)+>
<!ATTLIST hockey
  xmlns CDATA #FIXED ''
  database CDATA #REQUIRED>

<!ELEMENT league (conference+,(arenas,games)?)>
<!ATTLIST league
  xmlns CDATA #FIXED ''
  conferences CDATA #REQUIRED
  country CDATA #REQUIRED
  date CDATA #REQUIRED
  divisions CDATA #REQUIRED
  fullcountry CDATA #REQUIRED
  fullname CDATA #REQUIRED
  name CDATA #REQUIRED
  ordertype CDATA #REQUIRED
  playofffmt CDATA #REQUIRED>

<!ELEMENT conference (division)+>
<!ATTLIST conference
  xmlns CDATA #FIXED ''
  name CDATA #REQUIRED
  prefix CDATA #REQUIRED
  suffix CDATA #REQUIRED>

<!ELEMENT arenas (arena)+>
<!ATTLIST arenas
  xmlns CDATA #FIXED ''>

<!ELEMENT games (game)+>
<!ATTLIST games
  xmlns CDATA #FIXED ''>

<!ELEMENT division (team)+>
<!ATTLIST division
  xmlns CDATA #FIXED ''
  name CDATA #REQUIRED
  prefix CDATA #REQUIRED
  suffix CDATA #REQUIRED>

<!ELEMENT arena EMPTY>
<!ATTLIST arena
  xmlns CDATA #FIXED ''
  area CDATA #REQUIRED
  city CDATA #REQUIRED
  country CDATA #REQUIRED
  fullarea CDATA #REQUIRED
  fullcountry CDATA #REQUIRED
  name CDATA #REQUIRED>

<!ELEMENT game EMPTY>
<!ATTLIST game
  xmlns CDATA #FIXED ''
  atarena CDATA #REQUIRED
  awayteam CDATA #REQUIRED
  date CDATA #REQUIRED
  time CDATA #REQUIRED
  faceoffwins CDATA #REQUIRED
  goals CDATA #REQUIRED
  hits CDATA #REQUIRED
  hometeam CDATA #REQUIRED
  isplayoffgame CDATA #REQUIRED
  penalties CDATA #REQUIRED
  pims CDATA #REQUIRED
  ppgs CDATA #REQUIRED
  shgs CDATA #REQUIRED
  sogs CDATA #REQUIRED
  takeaways CDATA #REQUIRED>

<!ELEMENT team EMPTY>
<!ATTLIST team
  xmlns CDATA #FIXED ''
  area CDATA #REQUIRED
  arena CDATA #REQUIRED
  city CDATA #REQUIRED
  country CDATA #REQUIRED
  fullarea CDATA #REQUIRED
  fullcountry CDATA #REQUIRED
  name CDATA #REQUIRED
  prefix CDATA #REQUIRED
  suffix CDATA #REQUIRED
  affiliates CDATA #REQUIRED>
]>
<hockey xmlns="" database="./php/data/fhmt1y17-18.db3">
 <league xmlns="" name="HOL" fullname="Hockey League" country="USA" fullcountry="United States" date="20171001" playofffmt="Division=1,Conference=1" ordertype="ORDER BY Points DESC, GamesPlayed ASC, TWins DESC, Losses ASC, GoalsDifference DESC" conferences="yes" divisions="yes">
  <conference xmlns="" name="Conference 1" prefix="" suffix="">
   <division xmlns="" name="Division 1" prefix="" suffix="">
    <team xmlns="" city="Kansas City" area="MO" fullarea="Missouri" country="USA" fullcountry="United States" name="Flies" arena="KAN Arena" prefix="Kansas City" suffix="" affiliates="MIL:Milan Dazzle"/>
    <team xmlns="" city="Chicago" area="IL" fullarea="Illionis" country="USA" fullcountry="United States" name="Lampreys" arena="CHI Arena" prefix="Chicago" suffix="" affiliates="MIL:Moline Expositions"/>
   </division>
   <division xmlns="" name="Division 2" prefix="" suffix="">
    <team xmlns="" city="Ft. Wayne" area="IN" fullarea="Indiana" country="USA" fullcountry="United States" name="Whitecaps" arena="WHI Arena" prefix="Ft. Wayne" suffix="" affiliates="MIL:Kokomo Loggerheads"/>
    <team xmlns="" city="Minneapolis" area="MN" fullarea="Minnesota" country="USA" fullcountry="United States" name="Frogs" arena="MIN Arena" prefix="Minneapolis" suffix="" affiliates="MIL:Becker Winged Wheelers"/>
   </division>
  </conference>
  <conference xmlns="" name="Conference 2" prefix="" suffix="">
   <division xmlns="" name="Division 3" prefix="" suffix="">
    <team xmlns="" city="Columbus" area="OH" fullarea="Ohio" country="USA" fullcountry="United States" name="Passion" arena="COL Arena" prefix="Columbus" suffix="" affiliates="MIL:Toledo Pugs"/>
    <team xmlns="" city="Akron" area="OH" fullarea="Ohio" country="USA" fullcountry="United States" name="Cattlemen" arena="AKR Arena" prefix="Akron" suffix="" affiliates="MIL:Mason Caravans"/>
   </division>
   <division xmlns="" name="Division 4" prefix="" suffix="">
    <team xmlns="" city="Indianapolis" area="IN" fullarea="Indiana" country="USA" fullcountry="United States" name="Gears" arena="IND Arena" prefix="Indianapolis" suffix="" affiliates="MIL:Lawrence Walkers"/>
    <team xmlns="" city="Wichita" area="KS" fullarea="Kansas" country="USA" fullcountry="United States" name="Rail Hawks" arena="WIC Arena" prefix="Wichita" suffix="" affiliates="MIL:Garden City Jammers"/>
   </division>
  </conference>
 </league>
 <league xmlns="" name="MIL" fullname="Minor League" country="USA" fullcountry="United States" date="20171001" playofffmt="Division=1,Conference=1" ordertype="ORDER BY PCT DESC, GamesPlayed ASC, TWins DESC, Losses ASC, GoalsDifference DESC" conferences="yes" divisions="yes">
  <conference xmlns="" name="Conference 1" prefix="" suffix="">
   <division xmlns="" name="Division 1" prefix="" suffix="">
    <team xmlns="" city="Milan" area="MO" fullarea="Missouri" country="USA" fullcountry="United States" name="Dazzle" arena="MIL Arena" prefix="Milan" suffix="" affiliates="HOL:Kansas City Flies"/>
    <team xmlns="" city="Moline" area="IL" fullarea="Illionis" country="USA" fullcountry="United States" name="Expositions" arena="MOL Arena" prefix="Moline" suffix="" affiliates="HOL:Chicago Lampreys"/>
   </division>
   <division xmlns="" name="Division 2" prefix="" suffix="">
    <team xmlns="" city="Kokomo" area="IN" fullarea="Indiana" country="USA" fullcountry="United States" name="Loggerheads" arena="KOK Arena" prefix="Kokomo" suffix="" affiliates="HOL:Ft. Wayne Whitecaps"/>
    <team xmlns="" city="Becker" area="MN" fullarea="Minnesota" country="USA" fullcountry="United States" name="Winged Wheelers" arena="BEC Arena" prefix="Becker" suffix="" affiliates="HOL:Minneapolis Frogs"/>
   </division>
  </conference>
  <conference xmlns="" name="Conference 2" prefix="" suffix="">
   <division xmlns="" name="Division 3" prefix="" suffix="">
    <team xmlns="" city="Toledo" area="OH" fullarea="Ohio" country="USA" fullcountry="United States" name="Pugs" arena="TOL Arena" prefix="Toledo" suffix="" affiliates="HOL:Columbus Passion"/>
    <team xmlns="" city="Mason" area="OH" fullarea="Ohio" country="USA" fullcountry="United States" name="Caravans" arena="MAS Arena" prefix="Mason" suffix="" affiliates="HOL:Akron Cattlemen"/>
   </division>
   <division xmlns="" name="Division 4" prefix="" suffix="">
    <team xmlns="" city="Lawrence" area="IN" fullarea="Indiana" country="USA" fullcountry="United States" name="Walkers" arena="LAW Arena" prefix="Lawrence" suffix="" affiliates="HOL:Indianapolis Gears"/>
    <team xmlns="" city="Garden City" area="KS" fullarea="Kansas" country="USA" fullcountry="United States" name="Jammers" arena="GAR Arena" prefix="Garden City" suffix="" affiliates="HOL:Wichita Rail Hawks"/>
   </division>
  </conference>
 </league>
</hockey>
