<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hockey [

<!ELEMENT hockey (league)+>
<!ATTLIST hockey
  xmlns CDATA #FIXED ''
  database CDATA #REQUIRED>

<!ELEMENT league (conference+,(arenas,games)?)>
<!ATTLIST league
  xmlns CDATA #FIXED ''
  conferences CDATA #REQUIRED
  country CDATA #REQUIRED
  date CDATA #REQUIRED
  divisions CDATA #REQUIRED
  fullcountry CDATA #REQUIRED
  fullname CDATA #REQUIRED
  name CDATA #REQUIRED
  ordertype CDATA #REQUIRED
  playofffmt CDATA #REQUIRED>

<!ELEMENT conference (division)+>
<!ATTLIST conference
  xmlns CDATA #FIXED ''
  name CDATA #REQUIRED
  prefix CDATA #REQUIRED
  suffix CDATA #REQUIRED>

<!ELEMENT arenas (arena)+>
<!ATTLIST arenas
  xmlns CDATA #FIXED ''>

<!ELEMENT games (game)+>
<!ATTLIST games
  xmlns CDATA #FIXED ''>

<!ELEMENT division (team)+>
<!ATTLIST division
  xmlns CDATA #FIXED ''
  name CDATA #REQUIRED
  prefix CDATA #REQUIRED
  suffix CDATA #REQUIRED>

<!ELEMENT arena EMPTY>
<!ATTLIST arena
  xmlns CDATA #FIXED ''
  area CDATA #REQUIRED
  city CDATA #REQUIRED
  country CDATA #REQUIRED
  fullarea CDATA #REQUIRED
  fullcountry CDATA #REQUIRED
  name CDATA #REQUIRED>

<!ELEMENT game EMPTY>
<!ATTLIST game
  xmlns CDATA #FIXED ''
  atarena CDATA #REQUIRED
  awayteam CDATA #REQUIRED
  date CDATA #REQUIRED
  time CDATA #REQUIRED
  faceoffwins CDATA #REQUIRED
  goals CDATA #REQUIRED
  hits CDATA #REQUIRED
  hometeam CDATA #REQUIRED
  isplayoffgame CDATA #REQUIRED
  penalties CDATA #REQUIRED
  pims CDATA #REQUIRED
  ppgs CDATA #REQUIRED
  shgs CDATA #REQUIRED
  sogs CDATA #REQUIRED
  takeaways CDATA #REQUIRED>

<!ELEMENT team EMPTY>
<!ATTLIST team
  xmlns CDATA #FIXED ''
  area CDATA #REQUIRED
  arena CDATA #REQUIRED
  city CDATA #REQUIRED
  country CDATA #REQUIRED
  fullarea CDATA #REQUIRED
  fullcountry CDATA #REQUIRED
  name CDATA #REQUIRED
  prefix CDATA #REQUIRED
  suffix CDATA #REQUIRED
  affiliates CDATA #REQUIRED>
]>
<hockey xmlns="" database="./php/data/fhmt2y17-18.db3">
 <league xmlns="" name="HOL" fullname="Hockey League" country="USA" fullcountry="United States" date="20171001" playofffmt="Division=1,Conference=1" ordertype="ORDER BY Points DESC, GamesPlayed ASC, TWins DESC, Losses ASC, GoalsDifference DESC" conferences="yes" divisions="yes">
  <conference xmlns="" name="Conference 1" prefix="" suffix="">
   <division xmlns="" name="Division 1" prefix="" suffix="">
    <team xmlns="" city="Detroit" area="MI" fullarea="Michigan" country="USA" fullcountry="United States" name="Blasters" arena="DET Arena" prefix="Detroit" suffix="" affiliates="MIL:Northview Loggerheads"/>
    <team xmlns="" city="Indianapolis" area="IN" fullarea="Indiana" country="USA" fullcountry="United States" name="Sabres" arena="IND Arena" prefix="Indianapolis" suffix="" affiliates="MIL:Gulivoire Park Caravans"/>
   </division>
   <division xmlns="" name="Division 2" prefix="" suffix="">
    <team xmlns="" city="Chicago" area="IL" fullarea="Illionis" country="USA" fullcountry="United States" name="River Bandits" arena="CHI Arena" prefix="Chicago" suffix="" affiliates="MIL:Wheeling Ramblers"/>
    <team xmlns="" city="Kansas City" area="MO" fullarea="Missouri" country="USA" fullcountry="United States" name="Chariots" arena="KAN Arena" prefix="Kansas City" suffix="" affiliates="MIL:Columbia Skychiefs"/>
   </division>
  </conference>
  <conference xmlns="" name="Conference 2" prefix="" suffix="">
   <division xmlns="" name="Division 3" prefix="" suffix="">
    <team xmlns="" city="St. Paul" area="MN" fullarea="Minnesota" country="USA" fullcountry="United States" name="Smoking Guns" arena="SMO Arena" prefix="St. Paul" suffix="" affiliates="MIL:Winona Vipers"/>
    <team xmlns="" city="Minneapolis" area="MN" fullarea="Minnesota" country="USA" fullcountry="United States" name="Armada" arena="MIN Arena" prefix="Minneapolis" suffix="" affiliates="MIL:New Hope Chaos"/>
   </division>
   <division xmlns="" name="Division 4" prefix="" suffix="">
    <team xmlns="" city="Peoria" area="IL" fullarea="Illionis" country="USA" fullcountry="United States" name="Jammers" arena="PEO Arena" prefix="Peoria" suffix="" affiliates="MIL:Tinley Park Gappers"/>
    <team xmlns="" city="Joliet" area="IL" fullarea="Illionis" country="USA" fullcountry="United States" name="Gears" arena="JOL Arena" prefix="Chicago" suffix="" affiliates="MIL:Franklin Park Spirits"/>
   </division>
  </conference>
 </league>
 <league xmlns="" name="MIL" fullname="Minor League" country="USA" fullcountry="United States" date="20171001" playofffmt="Division=1,Conference=1" ordertype="ORDER BY PCT DESC, GamesPlayed ASC, TWins DESC, Losses ASC, GoalsDifference DESC" conferences="yes" divisions="yes">
  <conference xmlns="" name="Conference 1" prefix="" suffix="">
   <division xmlns="" name="Division 1" prefix="" suffix="">
    <team xmlns="" city="Northview" area="MI" fullarea="Michigan" country="USA" fullcountry="United States" name="Loggerheads" arena="NOR Arena" prefix="Northview" suffix="" affiliates="HOL:Detroit Blasters"/>
    <team xmlns="" city="Gulivoire Park" area="IN" fullarea="Indiana" country="USA" fullcountry="United States" name="Caravans" arena="GUL Arena" prefix="Gulivoire Park" suffix="" affiliates="HOL:Indianapolis Sabres"/>
   </division>
   <division xmlns="" name="Division 2" prefix="" suffix="">
    <team xmlns="" city="Wheeling" area="IL" fullarea="Illionis" country="USA" fullcountry="United States" name="Ramblers" arena="WHE Arena" prefix="Wheeling" suffix="" affiliates="HOL:Chicago River Bandits"/>
    <team xmlns="" city="Columbia" area="MO" fullarea="Missouri" country="USA" fullcountry="United States" name="Skychiefs" arena="COL Arena" prefix="Columbia" suffix="" affiliates="HOL:Kansas City Chariots"/>
   </division>
  </conference>
  <conference xmlns="" name="Conference 2" prefix="" suffix="">
   <division xmlns="" name="Division 3" prefix="" suffix="">
    <team xmlns="" city="Winona" area="MN" fullarea="Minnesota" country="USA" fullcountry="United States" name="Vipers" arena="WIN Arena" prefix="Winona" suffix="" affiliates="HOL:St. Paul Smoking Guns"/>
    <team xmlns="" city="New Hope" area="MN" fullarea="Minnesota" country="USA" fullcountry="United States" name="Chaos" arena="NEW Arena" prefix="New Hope" suffix="" affiliates="HOL:Minneapolis Armada"/>
   </division>
   <division xmlns="" name="Division 4" prefix="" suffix="">
    <team xmlns="" city="Tinley Park" area="IL" fullarea="Illionis" country="USA" fullcountry="United States" name="Gappers" arena="TIN Arena" prefix="Tinley Park" suffix="" affiliates="HOL:Peoria Jammers"/>
    <team xmlns="" city="Franklin Park" area="IL" fullarea="Illionis" country="USA" fullcountry="United States" name="Spirits" arena="FRA Arena" prefix="Franklin Park" suffix="" affiliates="HOL:Chicago Gears"/>
   </division>
  </conference>
 </league>
</hockey>
