<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hockey [

<!ELEMENT hockey (league)+>
<!ATTLIST hockey
  xmlns CDATA #FIXED ''
  database CDATA #REQUIRED>

<!ELEMENT league (conference+,(arenas,games)?)>
<!ATTLIST league
  xmlns CDATA #FIXED ''
  conferences CDATA #REQUIRED
  country CDATA #REQUIRED
  date CDATA #REQUIRED
  divisions CDATA #REQUIRED
  fullcountry CDATA #REQUIRED
  fullname CDATA #REQUIRED
  name CDATA #REQUIRED
  ordertype CDATA #REQUIRED
  playofffmt CDATA #REQUIRED>

<!ELEMENT conference (division)+>
<!ATTLIST conference
  xmlns CDATA #FIXED ''
  name CDATA #REQUIRED
  prefix CDATA #REQUIRED
  suffix CDATA #REQUIRED>

<!ELEMENT arenas (arena)+>
<!ATTLIST arenas
  xmlns CDATA #FIXED ''>

<!ELEMENT games (game)+>
<!ATTLIST games
  xmlns CDATA #FIXED ''>

<!ELEMENT division (team)+>
<!ATTLIST division
  xmlns CDATA #FIXED ''
  name CDATA #REQUIRED
  prefix CDATA #REQUIRED
  suffix CDATA #REQUIRED>

<!ELEMENT arena EMPTY>
<!ATTLIST arena
  xmlns CDATA #FIXED ''
  area CDATA #REQUIRED
  city CDATA #REQUIRED
  country CDATA #REQUIRED
  fullarea CDATA #REQUIRED
  fullcountry CDATA #REQUIRED
  name CDATA #REQUIRED>

<!ELEMENT game EMPTY>
<!ATTLIST game
  xmlns CDATA #FIXED ''
  atarena CDATA #REQUIRED
  awayteam CDATA #REQUIRED
  date CDATA #REQUIRED
  time CDATA #REQUIRED
  faceoffwins CDATA #REQUIRED
  goals CDATA #REQUIRED
  hits CDATA #REQUIRED
  hometeam CDATA #REQUIRED
  isplayoffgame CDATA #REQUIRED
  penalties CDATA #REQUIRED
  pims CDATA #REQUIRED
  ppgs CDATA #REQUIRED
  shgs CDATA #REQUIRED
  sogs CDATA #REQUIRED
  takeaways CDATA #REQUIRED>

<!ELEMENT team EMPTY>
<!ATTLIST team
  xmlns CDATA #FIXED ''
  area CDATA #REQUIRED
  arena CDATA #REQUIRED
  city CDATA #REQUIRED
  country CDATA #REQUIRED
  fullarea CDATA #REQUIRED
  fullcountry CDATA #REQUIRED
  name CDATA #REQUIRED
  prefix CDATA #REQUIRED
  suffix CDATA #REQUIRED
  affiliates CDATA #REQUIRED>
]>
<hockey xmlns="" database="./php/data/hockey15-16.db3">
 <league xmlns="" name="ECHL" fullname="ECHL" country="USA" fullcountry="United States" date="20151007" playofffmt="Division=1,Conference=5" ordertype="ORDER BY PCT DESC, GamesPlayed ASC, TWins DESC, Losses ASC, GoalsDifference DESC" conferences="yes" divisions="yes">
  <conference xmlns="" name="Eastern" prefix="" suffix="Conference">
   <division xmlns="" name="East" prefix="" suffix="Division">
    <team xmlns="" city="Elmira" area="NY" fullarea="New York" country="USA" fullcountry="United States" name="Jackals" arena="First Arena" prefix="Elmira" suffix="" affiliates="AHL:Rochester Americans,NHL:Buffalo Sabres"/>
    <team xmlns="" city="Reading" area="PA" fullarea="Pennsylvania" country="USA" fullcountry="United States" name="Royals" arena="Santander Arena" prefix="Reading" suffix="" affiliates="AHL:Lehigh Valley Phantoms,NHL:Philadelphia Flyers"/>
    <team xmlns="" city="Norfolk" area="VA" fullarea="Virginia" country="USA" fullcountry="United States" name="Admirals" arena="Norfolk Scope" prefix="Norfolk" suffix="" affiliates="AHL:Bakersfield Condors,NHL:Edmonton Oilers"/>
    <team xmlns="" city="Glens Falls" area="NY" fullarea="New York" country="USA" fullcountry="United States" name="Thunder" arena="Glens Falls Civic Center" prefix="Adirondack" suffix="" affiliates="AHL:Stockton Heat,NHL:Calgary Flames"/>
    <team xmlns="" city="Manchester" area="NH" fullarea="New Hampshire" country="USA" fullcountry="United States" name="Monarchs" arena="Verizon Wireless Arena" prefix="Manchester" suffix="" affiliates="AHL:Ontario Reign,NHL:Los Angeles Kings"/>
   </division>
   <division xmlns="" name="North" prefix="" suffix="Division">
    <team xmlns="" city="Kalamazoo" area="MI" fullarea="Michigan" country="USA" fullcountry="United States" name="Wings" arena="Wings Event Center" prefix="Kalamazoo" suffix="" affiliates="AHL:Lake Erie Monsters,NHL:Columbus Blue Jackets"/>
    <team xmlns="" city="Toledo" area="OH" fullarea="Ohio" country="USA" fullcountry="United States" name="Walleye" arena="Huntington Center" prefix="Toledo" suffix="" affiliates="AHL:Grand Rapids Griffins,NHL:Detroit Red Wings"/>
    <team xmlns="" city="Wheeling" area="WV" fullarea="West Virginia" country="USA" fullcountry="United States" name="Nailers" arena="WesBanco Arena" prefix="Wheeling" suffix="" affiliates="AHL:Wilkes-Barre/Scranton Penguins,NHL:Pittsburgh Penguins"/>
    <team xmlns="" city="Brampton" area="ON" fullarea="Ontario" country="CAN" fullcountry="Canada" name="Beast" arena="Powerade Centre" prefix="Brampton" suffix="" affiliates="AHL:St. John's IceCaps,NHL:Montreal Canadiens"/>
   </division>
   <division xmlns="" name="South" prefix="" suffix="Division">
    <team xmlns="" city="Duluth" area="GA" fullarea="Georgia" country="USA" fullcountry="United States" name="Gladiators" arena="Infinite Energy Arena" prefix="Atlanta" suffix="" affiliates="AHL:Providence Bruins,NHL:Boston Bruins"/>
    <team xmlns="" city="Greenville" area="SC" fullarea="South Carolina" country="USA" fullcountry="United States" name="Swamp Rabbits" arena="Bon Secours Wellness Arena" prefix="Greenville" suffix="" affiliates="AHL:Hartford Wolf Pack,NHL:New York Rangers"/>
    <team xmlns="" city="Estero" area="FL" fullarea="Florida" country="USA" fullcountry="United States" name="Everblades" arena="Germain Arena" prefix="Florida" suffix="" affiliates="AHL:Charlotte Checkers,NHL:Carolina Hurricanes"/>
    <team xmlns="" city="Orlando" area="FL" fullarea="Florida" country="USA" fullcountry="United States" name="Solar Bears" arena="Amway Center" prefix="Orlando" suffix="" affiliates="AHL:Toronto Marlies,NHL:Toronto Maple Leafs"/>
    <team xmlns="" city="North Charleston" area="SC" fullarea="South Carolina" country="USA" fullcountry="United States" name="Stingrays" arena="North Charleston Coliseum" prefix="South Carolina" suffix="" affiliates="AHL:Hershey Bears,NHL:Washington Capitals"/>
   </division>
  </conference>
  <conference xmlns="" name="Western" prefix="" suffix="Conference">
   <division xmlns="" name="Midwest" prefix="" suffix="Division">
    <team xmlns="" city="Moline" area="IL" fullarea="Illinois" country="USA" fullcountry="United States" name="Mallards" arena="iWireless Center" prefix="Quad City" suffix="" affiliates="AHL:Iowa Wild,NHL:Minnesota Wild"/>
    <team xmlns="" city="Evansville" area="IN" fullarea="Indiana" country="USA" fullcountry="United States" name="IceMen" arena="Ford Center" prefix="Evansville" suffix="" affiliates="AHL:Binghamton Senators,NHL:Ottawa Senators"/>
    <team xmlns="" city="Indianapolis" area="IN" fullarea="Indiana" country="USA" fullcountry="United States" name="Fuel" arena="Indiana Farmers Coliseum" prefix="Indy" suffix="" affiliates="AHL:Rockford IceHogs,NHL:Chicago Blackhawks"/>
    <team xmlns="" city="Fort Wayne" area="IN" fullarea="Indiana" country="USA" fullcountry="United States" name="Komets" arena="Allen County War Memorial Coliseum" prefix="Fort Wayne" suffix="" affiliates="AHL:San Antonio Rampage,NHL:Colorado Avalanche"/>
    <team xmlns="" city="Cincinnati" area="OH" fullarea="Ohio" country="USA" fullcountry="United States" name="Cyclones" arena="US Bank Arena" prefix="Cincinnati" suffix="" affiliates="AHL:Milwaukee Admirals,NHL:Nashville Predators"/>
   </division>
   <division xmlns="" name="Central" prefix="" suffix="Division">
    <team xmlns="" city="Wichita" area="KS" fullarea="Kansas" country="USA" fullcountry="United States" name="Thunder" arena="Intrust Bank Arena" prefix="Wichita" suffix="" affiliates="AHL:None,NHL:None"/>
    <team xmlns="" city="Allen" area="TX" fullarea="Texas" country="USA" fullcountry="United States" name="Americans" arena="Allen Event Center" prefix="Allen" suffix="" affiliates="AHL:San Jose Barracuda,NHL:San Jose Sharks"/>
    <team xmlns="" city="Tulsa" area="OK" fullarea="Oklahoma" country="USA" fullcountry="United States" name="Oilers" arena="BOK Center" prefix="Tulsa" suffix="" affiliates="AHL:Manitoba Moose,NHL:Winnipeg Jets"/>
    <team xmlns="" city="Independence" area="MO" fullarea="Missouri" country="USA" fullcountry="United States" name="Mavericks" arena="Silverstein Eye Centers Arena" prefix="Missouri" suffix="" affiliates="AHL:Bridgeport Sound Tigers,NHL:New York Islanders"/>
   </division>
   <division xmlns="" name="West" prefix="" suffix="Division">
    <team xmlns="" city="Anchorage" area="AK" fullarea="Alaska" country="USA" fullcountry="United States" name="Aces" arena="Sullivan Arena" prefix="Alaska" suffix="" affiliates="AHL:None,NHL:None"/>
    <team xmlns="" city="Boise" area="ID" fullarea="Idaho" country="USA" fullcountry="United States" name="Steelheads" arena="CenturyLink Arena" prefix="Idaho" suffix="" affiliates="AHL:Texas Stars,NHL:Dallas Stars"/>
    <team xmlns="" city="West Valley City" area="UT" fullarea="Utah" country="USA" fullcountry="United States" name="Grizzlies" arena="Maverik Center" prefix="Utah" suffix="" affiliates="AHL:San Diego Gulls,NHL:Anaheim Ducks"/>
    <team xmlns="" city="Loveland" area="CO" fullarea="Colorado" country="USA" fullcountry="United States" name="Eagles" arena="Budweiser Events Center" prefix="Colorado" suffix="" affiliates="AHL:None,NHL:None"/>
    <team xmlns="" city="Rapid City" area="SD" fullarea="South Dakota" country="USA" fullcountry="United States" name="Rush" arena="Rushmore Plaza Civic Center" prefix="Rapid City" suffix="" affiliates="AHL:Springfield Falcons,NHL:Arizona Coyotes"/>
   </division>
  </conference>
 </league>
 <league xmlns="" name="AHL" fullname="American Hockey League" country="USA" fullcountry="United States" date="20151009" playofffmt="Division=4" ordertype="ORDER BY PCT DESC, GamesPlayed ASC, TWins DESC, Losses ASC, GoalsDifference DESC" conferences="yes" divisions="yes">
  <conference xmlns="" name="Eastern" prefix="" suffix="Conference">
   <division xmlns="" name="Atlantic" prefix="" suffix="Division">
    <team xmlns="" city="Bridgeport" area="CT" fullarea="Connecticut" country="USA" fullcountry="United States" name="Sound Tigers" arena="Webster Bank Arena" prefix="Bridgeport" suffix="" affiliates="ECHL:Missouri Mavericks,NHL:New York Islanders"/>
    <team xmlns="" city="Hartford" area="CT" fullarea="Connecticut" country="USA" fullcountry="United States" name="Wolf Pack" arena="XL Center" prefix="Hartford" suffix="" affiliates="ECHL:Greenville Swamp Rabbits,NHL:New York Rangers"/>
    <team xmlns="" city="Hershey" area="PA" fullarea="Pennsylvania" country="USA" fullcountry="United States" name="Bears" arena="Giant Center" prefix="Hershey" suffix="" affiliates="ECHL:South Carolina Stingrays,NHL:Washington Capitals"/>
    <team xmlns="" city="Allentown" area="PA" fullarea="Pennsylvania" country="USA" fullcountry="United States" name="Phantoms" arena="PPL Center" prefix="Lehigh Valley" suffix="" affiliates="ECHL:Reading Royals,NHL:Philadelphia Flyers"/>
    <team xmlns="" city="Portland" area="ME" fullarea="Maine" country="USA" fullcountry="United States" name="Pirates" arena="Cross Insurance Arena" prefix="Portland" suffix="" affiliates="ECHL:None,NHL:Florida Panthers"/>
    <team xmlns="" city="Providence" area="RI" fullarea="Rhode Island" country="USA" fullcountry="United States" name="Bruins" arena="Dunkin' Donuts Center" prefix="Providence" suffix="" affiliates="ECHL:Atlanta Gladiators,NHL:Boston Bruins"/>
    <team xmlns="" city="Springfield" area="MA" fullarea="Massachusetts" country="USA" fullcountry="United States" name="Falcons" arena="MassMutual Center" prefix="Springfield" suffix="" affiliates="ECHL:Rapid City Rush,NHL:Arizona Coyotes"/>
    <team xmlns="" city="Wilkes-Barre" area="PA" fullarea="Pennsylvania" country="USA" fullcountry="United States" name="Penguins" arena="Mohegan Sun Arena" prefix="Wilkes-Barre/Scranton" suffix="" affiliates="ECHL:Wheeling Nailers,NHL:Pittsburgh Penguins"/>
   </division>
   <division xmlns="" name="North" prefix="" suffix="Division">
    <team xmlns="" city="Albany" area="NY" fullarea="New York" country="USA" fullcountry="United States" name="Devils" arena="Times Union Center" prefix="Albany" suffix="" affiliates="ECHL:None,NHL:New Jersey Devils"/>
    <team xmlns="" city="Binghamton" area="NY" fullarea="New York" country="USA" fullcountry="United States" name="Senators" arena="Floyd L. Maines Veterans Memorial Arena" prefix="Binghamton" suffix="" affiliates="ECHL:Evansville IceMen,NHL:Ottawa Senators"/>
    <team xmlns="" city="Rochester" area="NY" fullarea="New York" country="USA" fullcountry="United States" name="Americans" arena="Blue Cross Arena" prefix="Rochester" suffix="" affiliates="ECHL:Elmira Jackals,NHL:Buffalo Sabres"/>
    <team xmlns="" city="St. John's" area="NL" fullarea="Newfoundland and Labrador" country="CAN" fullcountry="Canada" name="IceCaps" arena="Mile One Centre" prefix="St. John's" suffix="" affiliates="ECHL:Brampton Beast,NHL:Montreal Canadiens"/>
    <team xmlns="" city="Syracuse" area="NY" fullarea="New York" country="USA" fullcountry="United States" name="Crunch" arena="Oncenter War Memorial Arena" prefix="Syracuse" suffix="" affiliates="ECHL:None,NHL:Tampa Bay Lightning"/>
    <team xmlns="" city="Toronto" area="ON" fullarea="Ontario" country="CAN" fullcountry="Canada" name="Marlies" arena="Ricoh Coliseum" prefix="Toronto" suffix="" affiliates="ECHL:Orlando Solar Bears,NHL:Toronto Maple Leafs"/>
    <team xmlns="" city="Utica" area="NY" fullarea="New York" country="USA" fullcountry="United States" name="Comets" arena="Utica Memorial Auditorium" prefix="Utica" suffix="" affiliates="ECHL:None,NHL:Vancouver Canucks"/>
   </division>
  </conference>
  <conference xmlns="" name="Western" prefix="" suffix="Conference">
   <division xmlns="" name="Central" prefix="" suffix="Division">
    <team xmlns="" city="Charlotte" area="NC" fullarea="North Carolina" country="USA" fullcountry="United States" name="Checkers" arena="Bojangles Coliseum" prefix="Charlotte" suffix="" affiliates="ECHL:Florida Everblades,NHL:Carolina Hurricanes"/>
    <team xmlns="" city="Rosemont" area="IL" fullarea="Illinois" country="USA" fullcountry="United States" name="Wolves" arena="Allstate Arena" prefix="Chicago" suffix="" affiliates="ECHL:None,NHL:St. Louis Blues"/>
    <team xmlns="" city="Grand Rapids" area="MI" fullarea="Michigan" country="USA" fullcountry="United States" name="Griffins" arena="Van Andel Arena" prefix="Grand Rapids" suffix="" affiliates="ECHL:Toledo Walleye,NHL:Detroit Red Wings"/>
    <team xmlns="" city="Des Moines" area="IA" fullarea="Iowa" country="USA" fullcountry="United States" name="Wild" arena="Wells Fargo Arena" prefix="Iowa" suffix="" affiliates="ECHL:Quad City Mallards,NHL:Minnesota Wild"/>
    <team xmlns="" city="Cleveland" area="OH" fullarea="Ohio" country="USA" fullcountry="United States" name="Monsters" arena="Quicken Loans Arena" prefix="Lake Erie" suffix="" affiliates="ECHL:Kalamazoo Wings,NHL:Columbus Blue Jackets"/>
    <team xmlns="" city="Winnipeg" area="MB" fullarea="Manitoba" country="CAN" fullcountry="Canada" name="Moose" arena="MTS Centre" prefix="Manitoba" suffix="" affiliates="ECHL:Tulsa Oilers,NHL:Winnipeg Jets"/>
    <team xmlns="" city="Milwaukee" area="WI" fullarea="Wisconsin" country="USA" fullcountry="United States" name="Admirals" arena="BMO Harris Bradley Center" prefix="Milwaukee" suffix="" affiliates="ECHL:Cincinnati Cyclones,NHL:Nashville Predators"/>
    <team xmlns="" city="Rockford" area="IL" fullarea="Illinois" country="USA" fullcountry="United States" name="IceHogs" arena="BMO Harris Bank Center" prefix="Rockford" suffix="" affiliates="ECHL:Indy Fuel,NHL:Chicago Blackhawks"/>
   </division>
   <division xmlns="" name="Pacific" prefix="" suffix="Division">
    <team xmlns="" city="Bakersfield" area="CA" fullarea="California" country="USA" fullcountry="United States" name="Condors" arena="Rabobank Arena" prefix="Bakersfield" suffix="" affiliates="ECHL:Norfolk Admirals,NHL:Edmonton Oilers"/>
    <team xmlns="" city="Ontario" area="CA" fullarea="California" country="USA" fullcountry="United States" name="Reign" arena="Citizens Business Bank Arena" prefix="Ontario" suffix="" affiliates="ECHL:Manchester Monarchs,NHL:Los Angeles Kings"/>
    <team xmlns="" city="San Antonio" area="TX" fullarea="Texas" country="USA" fullcountry="United States" name="Rampage" arena="AT&amp;T Center" prefix="San Antonio" suffix="" affiliates="ECHL:Fort Wayne Komets,NHL:Colorado Avalanche"/>
    <team xmlns="" city="San Diego" area="CA" fullarea="California" country="USA" fullcountry="United States" name="Gulls" arena="Valley View Casino Center" prefix="San Diego" suffix="" affiliates="ECHL:Utah Grizzlies,NHL:Anaheim Ducks"/>
    <team xmlns="" city="San Jose" area="CA" fullarea="California" country="USA" fullcountry="United States" name="Barracuda" arena="SAP Center" prefix="San Jose" suffix="" affiliates="ECHL:Allen Americans,NHL:San Jose Sharks"/>
    <team xmlns="" city="Stockton" area="CA" fullarea="California" country="USA" fullcountry="United States" name="Heat" arena="Stockton Arena" prefix="Stockton" suffix="" affiliates="ECHL:Adirondack Thunder,NHL:Calgary Flames"/>
    <team xmlns="" city="Cedar Park" area="TX" fullarea="Texas" country="USA" fullcountry="United States" name="Stars" arena="Cedar Park Center" prefix="Texas" suffix="" affiliates="ECHL:Idaho Steelheads,NHL:Dallas Stars"/>
   </division>
  </conference>
  <arenas xmlns="">
   <arena xmlns="" city="West Sacramento" area="CA" fullarea="California" country="USA" fullcountry="United States" name="Raley Field"/>
  </arenas>
 </league>
 <league xmlns="" name="NHL" fullname="National Hockey League" country="USA" fullcountry="United States" date="20151007" playofffmt="Division=3,Conference=2" ordertype="ORDER BY Points DESC, GamesPlayed ASC, TWins DESC, Losses ASC, GoalsDifference DESC" conferences="yes" divisions="yes">
  <conference xmlns="" name="Eastern" prefix="" suffix="Conference">
   <division xmlns="" name="Atlantic" prefix="" suffix="Division">
    <team xmlns="" city="Boston" area="MA" fullarea="Massachusetts" country="USA" fullcountry="United States" name="Bruins" arena="TD Garden" prefix="Boston" suffix="" affiliates="ECHL:Atlanta Gladiators,AHL:Providence Bruins"/>
    <team xmlns="" city="Buffalo" area="NY" fullarea="New York" country="USA" fullcountry="United States" name="Sabres" arena="First Niagara Center" prefix="Buffalo" suffix="" affiliates="ECHL:Elmira Jackals,AHL:Rochester Americans"/>
    <team xmlns="" city="Detroit" area="MI" fullarea="Michigan" country="USA" fullcountry="United States" name="Red Wings" arena="Joe Louis Arena" prefix="Detroit" suffix="" affiliates="ECHL:Toledo Walleye,AHL:Grand Rapids Griffins"/>
    <team xmlns="" city="Sunrise" area="FL" fullarea="Florida" country="USA" fullcountry="United States" name="Panthers" arena="BB&amp;T Center" prefix="Florida" suffix="" affiliates="ECHL:None,AHL:Portland Pirates"/>
    <team xmlns="" city="Montreal" area="QC" fullarea="Quebec" country="CAN" fullcountry="Canada" name="Canadiens" arena="Bell Centre" prefix="Montreal" suffix="" affiliates="ECHL:Brampton Beast,AHL:St. John's Icecaps"/>
    <team xmlns="" city="Ottawa" area="ON" fullarea="Ontario" country="CAN" fullcountry="Canada" name="Senators" arena="Canadian Tire Centre" prefix="Ottawa" suffix="" affiliates="ECHL:Evansville IceMen,AHL:Binghamton Senators"/>
    <team xmlns="" city="Tampa Bay" area="FL" fullarea="Florida" country="USA" fullcountry="United States" name="Lightning" arena="Amalie Arena" prefix="Tampa Bay" suffix="" affiliates="ECHL:None,AHL:Syracuse Crunch"/>
    <team xmlns="" city="Toronto" area="ON" fullarea="Ontario" country="CAN" fullcountry="Canada" name="Maple Leafs" arena="Air Canada Centre" prefix="Toronto" suffix="" affiliates="ECHL:Orlando Solar Bears,AHL:Toronto Marlies"/>
   </division>
   <division xmlns="" name="Metropolitan" prefix="" suffix="Division">
    <team xmlns="" city="Carolina" area="NC" fullarea="North Carolina" country="USA" fullcountry="United States" name="Hurricanes" arena="PNC Arena" prefix="Carolina" suffix="" affiliates="ECHL:Florida Everblades,AHL:Charlotte Checkers"/>
    <team xmlns="" city="Columbus" area="OH" fullarea="Ohio" country="USA" fullcountry="United States" name="Blue Jackets" arena="Nationwide Arena" prefix="Columbus" suffix="" affiliates="ECHL:Kalamazoo Wings,AHL:Lake Erie Monsters"/>
    <team xmlns="" city="New Jersey" area="NJ" fullarea="New Jersey" country="USA" fullcountry="United States" name="Devils" arena="Prudential Center" prefix="New Jersey" suffix="" affiliates="ECHL:None,AHL:Albany Devils"/>
    <team xmlns="" city="New York City" area="NY" fullarea="New York" country="USA" fullcountry="United States" name="Islanders" arena="Barclays Center" prefix="New York" suffix="" affiliates="ECHL:Missouri Mavericks,AHL:Bridgeport Sound Tigers"/>
    <team xmlns="" city="New York City" area="NY" fullarea="New York" country="USA" fullcountry="United States" name="Rangers" arena="Madison Square Garden" prefix="New York" suffix="" affiliates="ECHL:Greenville Swamp Rabbits,AHL:Hartford Wolf Pack"/>
    <team xmlns="" city="Philadelphia" area="PA" fullarea="Pennsylvania" country="USA" fullcountry="United States" name="Flyers" arena="Wells Fargo Center" prefix="Philadelphia" suffix="" affiliates="ECHL:Reading Royals,AHL:Lehigh Valley Phantoms"/>
    <team xmlns="" city="Pittsburgh" area="PA" fullarea="Pennsylvania" country="USA" fullcountry="United States" name="Penguins" arena="Consol Energy Center" prefix="Pittsburgh" suffix="" affiliates="ECHL:Wheeling Nailers,AHL:Wilkes-Barre/Scranton Penguins"/>
    <team xmlns="" city="Washington" area="DC" fullarea="District of Columbia" country="USA" fullcountry="United States" name="Capitals" arena="Verizon Center" prefix="Washington" suffix="" affiliates="ECHL:South Carolina Stingrays,AHL:Hershey Bears"/>
   </division>
  </conference>
  <conference xmlns="" name="Western" prefix="" suffix="Conference">
   <division xmlns="" name="Central" prefix="" suffix="Division">
    <team xmlns="" city="Chicago" area="IL" fullarea="Illinois" country="USA" fullcountry="United States" name="Blackhawks" arena="United Center" prefix="Chicago" suffix="" affiliates="ECHL:Indy Fuel,AHL:Rockford IceHogs"/>
    <team xmlns="" city="Denver" area="CO" fullarea="Colorado" country="USA" fullcountry="United States" name="Avalanche" arena="Pepsi Center" prefix="Colorado" suffix="" affiliates="ECHL:Fort Wayne Komets,AHL:San Antonio Rampage"/>
    <team xmlns="" city="Dallas" area="TX" fullarea="Texas" country="USA" fullcountry="United States" name="Stars" arena="American Airlines Center" prefix="Dallas" suffix="" affiliates="ECHL:Idaho Steelheads,AHL:Texas Stars"/>
    <team xmlns="" city="St. Paul" area="MN" fullarea="Minnesota" country="USA" fullcountry="United States" name="Wild" arena="Xcel Energy Center" prefix="Minnesota" suffix="" affiliates="ECHL:Quad City Mallards,AHL:Iowa Wild"/>
    <team xmlns="" city="Nashville" area="TN" fullarea="Tennessee" country="USA" fullcountry="United States" name="Predators" arena="Bridgestone Arena" prefix="Nashville" suffix="" affiliates="ECHL:Cincinnati Cyclones,AHL:Milwaukee Admirals"/>
    <team xmlns="" city="St. Louis" area="MO" fullarea="Missouri" country="USA" fullcountry="United States" name="Blues" arena="Scottrade Center" prefix="St. Louis" suffix="" affiliates="ECHL:None,AHL:Chicago Wolves"/>
    <team xmlns="" city="Winnipeg" area="MB" fullarea="Manitoba" country="CAN" fullcountry="Canada" name="Jets" arena="MTS Centre" prefix="Winnipeg" suffix="" affiliates="ECHL:Tulsa Oilers,AHL:Manitoba Moose"/>
   </division>
   <division xmlns="" name="Pacific" prefix="" suffix="Division">
    <team xmlns="" city="Anaheim" area="CA" fullarea="California" country="USA" fullcountry="United States" name="Ducks" arena="Honda Center" prefix="Anaheim" suffix="" affiliates="ECHL:Utah Grizzlies,AHL:San Diego Gulls"/>
    <team xmlns="" city="Glendale" area="AZ" fullarea="Arizona" country="USA" fullcountry="United States" name="Coyotes" arena="Gila River Arena" prefix="Arizona" suffix="" affiliates="ECHL:Rapid City Rush,AHL:Springfield Falcons"/>
    <team xmlns="" city="Calgary" area="AB" fullarea="Alberta" country="CAN" fullcountry="Canada" name="Flames" arena="Scotiabank Saddledome" prefix="Calgary" suffix="" affiliates="ECHL:Adirondack Thunder,AHL:Stockton Heat"/>
    <team xmlns="" city="Edmonton" area="AB" fullarea="Alberta" country="CAN" fullcountry="Canada" name="Oilers" arena="Rexall Place" prefix="Edmonton" suffix="" affiliates="ECHL:Norfolk Admirals,AHL:Bakersfield Condors"/>
    <team xmlns="" city="Los Angeles" area="CA" fullarea="California" country="USA" fullcountry="United States" name="Kings" arena="Staples Center" prefix="Los Angeles" suffix="" affiliates="ECHL:Manchester Monarchs,AHL:Ontario Reign"/>
    <team xmlns="" city="San Jose" area="CA" fullarea="California" country="USA" fullcountry="United States" name="Sharks" arena="SAP Center" prefix="San Jose" suffix="" affiliates="ECHL:Allen Americans,AHL:San Jose Barracuda"/>
    <team xmlns="" city="Vancouver" area="BC" fullarea="British Columbia" country="CAN" fullcountry="Canada" name="Canucks" arena="Rogers Arena" prefix="Vancouver" suffix="" affiliates="ECHL:None,AHL:Utica Comets"/>
   </division>
  </conference>
  <arenas xmlns="">
   <arena xmlns="" city="Foxborough" area="MA" fullarea="Massachusetts" country="USA" fullcountry="United States" name="Gillette Stadium"/>
   <arena xmlns="" city="Minneapolis" area="MN" fullarea="Minnesota" country="USA" fullcountry="United States" name="TCF Bank Stadium"/>
   <arena xmlns="" city="Denver" area="CO" fullarea="Colorado" country="USA" fullcountry="United States" name="Coors Field"/>
  </arenas>
 </league>
</hockey>
